<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerSubscription.DAL\CustomerSubscription.DAL.csproj" />
    <ProjectReference Include="..\CustomerSubscription.Shared\CustomerSubscription.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Interfaces\" />
  </ItemGroup>
</Project>
